name: Terramorph
favicon: null
layout_spectrum: 0.41511583095416427
typography_spectrum: 0.5365132177248597
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.1916037353221327
  lightness: 0.503677963744849
  saturation: 0.3556595607660711
  rhythmicContrast: 0.5415255634579808
purpose: []
